Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import scipy.linalg.lapack as lapack
x = V.copy()
c, info = lapack.dpotrf(x)
lapack.dpotri(c, overwrite_c=1)
c + c.T - np.diag(c.diagonal())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31merror[0m                                     Traceback (most recent call last)
Cell [0;32mIn[8], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinalg[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlapack[39;00m [38;5;28;01mas[39;00m [38;5;21;01mlapack[39;00m
[1;32m      2[0m x [38;5;241m=[39m V[38;5;241m.[39mcopy()
[0;32m----> 3[0m c, info [38;5;241m=[39m [43mlapack[49m[38;5;241;43m.[39;49m[43mdpotrf[49m[43m([49m[43mx[49m[43m)[49m
[1;32m      4[0m lapack[38;5;241m.[39mdpotri(c, overwrite_c[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      5[0m c [38;5;241m+[39m c[38;5;241m.[39mT [38;5;241m-[39m np[38;5;241m.[39mdiag(c[38;5;241m.[39mdiagonal())

[0;31merror[0m: (shape(a,0)==shape(a,1)) failed for 1st argument a

