Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

start = "2016-01-01"
symbol_0 = "^TNX" # Á±≥ÂõΩ10Âπ¥„ÇÇ„ÅÆÂõΩÂÇµ
symbol_M = "^GSPC" # S&P500
symbol_m = "MCD" # „Éû„ÇØ„Éâ„Éä„É´„Éâ

symbols = [symbol_0, symbol_M, symbol_m]
df_price = yf.download(symbols, start=start)["Adj Close"]
df_price
------------------


Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m/usr/local/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3577[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [1;32mIn[6], line 4[0m
    import yfinance as yf[0m

[0m  File [1;32m/usr/local/lib/python3.10/site-packages/yfinance/__init__.py:30[0m
    from .screener.screener import Screener[0m

[0;36m  File [0;32m/usr/local/lib/python3.10/site-packages/yfinance/screener/__init__.py:1[0;36m
[0;31m    from .screener import Screener[0;36m

[0;36m  File [0;32m/usr/local/lib/python3.10/site-packages/yfinance/screener/screener.py:101[0;36m[0m
[0;31m    logger.error(f"Failed to get screener data for '{self._body.get('query', "query not set")}' reason: {e}")[0m
[0m                                                                              ^[0m
[0;31mSyntaxError[0m[0;31m:[0m f-string: unmatched '('


