Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from rdrobust import rdrobust, rdbwselect, rdplot
import pandas as pd

### Load data base
rdrobust_senate = pd.read_csv("https://raw.githubusercontent.com/rdpackages/rdrobust/master/Python/rdrobust_senate.csv")

# Define the variblrs
margin = rdrobust_senate.margin
vote = rdrobust_senate.vote

### rdplot with 95% confidence intervals
rdplot(y=vote, x=margin, binselect="es", ci=95, 
         title="RD Plot: U.S. Senate Election Data", 
         y_label="Vote Share in Election at time t+2",
         x_label="Vote Share in Election at time t")

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[4], line 12[0m
[1;32m      9[0m vote [38;5;241m=[39m rdrobust_senate[38;5;241m.[39mvote
[1;32m     11[0m [38;5;66;03m### rdplot with 95% confidence intervals[39;00m
[0;32m---> 12[0m [43mrdplot[49m[43m([49m[43my[49m[38;5;241;43m=[39;49m[43mvote[49m[43m,[49m[43m [49m[43mx[49m[38;5;241;43m=[39;49m[43mmargin[49m[43m,[49m[43m [49m[43mbinselect[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mes[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mci[49m[38;5;241;43m=[39;49m[38;5;241;43m95[39;49m[43m,[49m[43m [49m
[1;32m     13[0m [43m         [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mRD Plot: U.S. Senate Election Data[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m     14[0m [43m         [49m[43my_label[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mVote Share in Election at time t+2[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m     15[0m [43m         [49m[43mx_label[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mVote Share in Election at time t[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/rdrobust/rdplot.py:737[0m, in [0;36mrdplot[0;34m(y, x, c, p, nbins, binselect, scale, kernel, weights, h, covs, covs_eval, covs_drop, support, subset, masspoints, hide, ci, shade, title, x_label, y_label, x_lim, y_lim, col_dots, col_lines)[0m
[1;32m    729[0m         temp_plot [38;5;241m=[39m (temp_plot [38;5;241m+[39m
[1;32m    730[0m                      geom_ribbon(data[38;5;241m=[39mdata_bins, mapping [38;5;241m=[39m aes(x[38;5;241m=[39mrdplot_mean_bin, ymin[38;5;241m=[39mrdplot_cil_bin, ymax[38;5;241m=[39mrdplot_cir_bin)))
[1;32m    732[0m     temp_plot  [38;5;241m=[39m (temp_plot [38;5;241m+[39m labs(x [38;5;241m=[39m x_label, y [38;5;241m=[39m y_label) [38;5;241m+[39m ggtitle(title)[38;5;241m+[39m
[1;32m    733[0m                   coord_cartesian(xlim [38;5;241m=[39m x_lim, ylim [38;5;241m=[39m y_lim) [38;5;241m+[39m
[1;32m    734[0m                   theme(legend_position [38;5;241m=[39m [38;5;124m"[39m[38;5;124mNone[39m[38;5;124m"[39m) [38;5;241m+[39m
[1;32m    735[0m                   geom_vline(xintercept [38;5;241m=[39m c, size [38;5;241m=[39m [38;5;241m0.5[39m)) 
[0;32m--> 737[0m     [38;5;28;43mprint[39;49m[43m([49m[43mtemp_plot[49m[43m)[49m
[1;32m    739[0m rdplot_min_bin_l [38;5;241m=[39m jumps_l[[38;5;241m0[39m:J_star_l]
[1;32m    740[0m rdplot_max_bin_l [38;5;241m=[39m jumps_l[[38;5;241m1[39m:(J_star_l [38;5;241m+[39m [38;5;241m1[39m)]

File [0;32m/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/plotnine/ggplot.py:105[0m, in [0;36mggplot.__str__[0;34m(self)[0m
[1;32m    101[0m [38;5;28;01mdef[39;00m [38;5;21m__str__[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mstr[39m:
[1;32m    102[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    103[0m [38;5;124;03m    Print/show the plot[39;00m
[1;32m    104[0m [38;5;124;03m    """[39;00m
[0;32m--> 105[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdraw[49m[43m([49m[43mshow[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    107[0m     [38;5;66;03m# Return and empty string so that print(p) is "pretty"[39;00m
[1;32m    108[0m     [38;5;28;01mreturn[39;00m [38;5;124m"[39m[38;5;124m"[39m

File [0;32m/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/plotnine/ggplot.py:211[0m, in [0;36mggplot.draw[0;34m(self, show)[0m
[1;32m    197[0m [38;5;28;01mdef[39;00m [38;5;21mdraw[39m([38;5;28mself[39m, show: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m) [38;5;241m-[39m[38;5;241m>[39m Figure:
[1;32m    198[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    199[0m [38;5;124;03m    Render the complete plot[39;00m
[1;32m    200[0m 
[0;32m   (...)[0m
[1;32m    209[0m [38;5;124;03m        Matplotlib figure[39;00m
[1;32m    210[0m [38;5;124;03m    """[39;00m
[0;32m--> 211[0m     [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_mpl[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlayout_engine[39;00m [38;5;28;01mimport[39;00m PlotnineLayoutEngine
[1;32m    213[0m     [38;5;66;03m# Do not draw if drawn already.[39;00m
[1;32m    214[0m     [38;5;66;03m# This prevents a needless error when reusing[39;00m
[1;32m    215[0m     [38;5;66;03m# figure & axes in the jupyter notebook.[39;00m
[1;32m    216[0m     [38;5;28;01mif[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m, [38;5;124m"[39m[38;5;124mfigure[39m[38;5;124m"[39m):

File [0;32m/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/plotnine/_mpl/layout_engine.py:6[0m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mtyping[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdataclasses[39;00m [38;5;28;01mimport[39;00m asdict, dataclass
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlayout_engine[39;00m [38;5;28;01mimport[39;00m LayoutEngine
[1;32m      8[0m [38;5;28;01mif[39;00m typing[38;5;241m.[39mTYPE_CHECKING:
[1;32m      9[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Optional

[0;31mModuleNotFoundError[0m: No module named 'matplotlib.layout_engine'

